import assert from 'node:assert/strict'
import { createRequire } from 'node:module'
import { mkdir } from 'node:fs/promises'
const { chromium } = createRequire(process.env.TTF_PLAYWRIGHT_PACKAGE_JSON)('playwright')
const browser = await chromium.launch({ executablePath: process.env.TTF_BROWSER_PATH, headless: true })
await mkdir('.impeccable/review', { recursive: true })
try {
  for (const [name, width, height] of [['desktop', 1600, 1000], ['mobile', 390, 844], ['tablet', 820, 1180]]) {
    const context = await browser.newContext({ viewport: { width, height }, reducedMotion: 'reduce' })
    await context.addInitScript(() => { try { sessionStorage.setItem('ttf-intro-seen', '1') } catch {} })
    const page = await context.newPage(), errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.goto('http://127.0.0.1:5173/#works')
    await page.locator('.map-folio').first().waitFor()
    assert.equal(await page.locator('.map-folio').count(), 3)
    assert.equal(await page.locator('.image-trail').count(), 0)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
    await page.screenshot({ path: `.impeccable/review/${name}.png` })
    const trigger = page.locator('.map-folio-cover').first()
    await trigger.click()
    await page.locator('.map-reader-image').evaluate(img => img.decode())
    await page.waitForFunction(() => document.querySelector('.map-reader-image')?.getBoundingClientRect().width > 200)
    const viewport = page.getByTestId('map-viewport')
    assert.equal(await page.locator('#root').evaluate(root => root.inert), true)
    const image = page.locator('.map-reader-image')
    assert.ok((await image.getAttribute('src')).includes('collection/'))
    await page.getByRole('button', { name: '放大地图', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('.map-reader-tools output').textContent === '150%')
    assert.equal(await page.locator('.map-minimap').count(), 1)
    const before = await image.getAttribute('style')
    const box = await viewport.boundingBox()
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
    await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 90, box.y + box.height / 2 + 50, { steps: 8 }); await page.mouse.up()
    await page.waitForTimeout(100)
    assert.notEqual(await image.getAttribute('style'), before)
    await page.mouse.wheel(0, -450)
    await page.waitForFunction(() => parseInt(document.querySelector('.map-reader-tools output').textContent) > 150)
    await page.getByRole('button', { name: '查看全图', exact: true }).click()
    await page.waitForFunction(() => document.querySelector('.map-reader-tools output').textContent === '100%')
    await viewport.dblclick()
    await page.waitForFunction(() => document.querySelector('.map-reader-tools output').textContent === '250%')
    for (let i = 0; i < 12; i++) { await page.keyboard.press('Tab'); assert.equal(await page.evaluate(() => !!document.activeElement.closest('.map-reader')), true) }
    await page.screenshot({ path: `.impeccable/review/reader-${name}.png` })
    await page.keyboard.press('Escape')
    assert.equal(await page.locator('.map-reader').count(), 0)
    assert.equal(await page.locator('#root').evaluate(root => root.inert), false)
    assert.equal(await trigger.evaluate(node => document.activeElement === node), true)
    await page.getByRole('button', { name: '正史地图1', exact: false }).click()
    assert.equal(await page.locator('.map-folio').count(), 1)
    await page.locator('.map-folio-author').first().click()
    await page.locator('#member h1').waitFor()
    await page.screenshot({ path: `.impeccable/review/member-${name}.png` })
    assert.equal(await page.locator('#member img').nth(1).evaluate(img => getComputedStyle(img).objectFit), 'contain')
    await page.getByRole('button', { name: '← 返回作品集', exact: true }).click()
    await page.locator('.map-folio').first().waitFor()
    assert.equal(await page.locator('.map-folio').count(), 1)
    await page.goto('http://127.0.0.1:5173/#home')
    await page.locator('#home h1').waitFor()
    await page.waitForTimeout(1800)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
    await page.screenshot({ path: `.impeccable/review/home-${name}.png` })
    if (width < 768) { const cta = await page.locator('.atlas-enter-link').boundingBox(); assert.ok(cta.y + cta.height < height, 'mobile CTA should be in first viewport') }
    assert.deepEqual(errors, [])
    console.log(`${name}: three real works; zoom, wheel, drag, reset, double click, modal focus, filter return and layout passed`)
    await context.close()
  }
  // Real touch events in an isolated browser, not fabricated DOM mouse events.
  const context = await browser.newContext({ viewport: { width:390, height:844 }, hasTouch:true, isMobile:true, reducedMotion:'reduce' })
  await context.addInitScript(() => { try { sessionStorage.setItem('ttf-intro-seen','1') } catch {} })
  const page = await context.newPage()
  await page.goto('http://127.0.0.1:5173/#works'); await page.locator('.map-folio-cover').first().click()
  await page.locator('.map-reader-image').evaluate(img => img.decode())
  const box = await page.getByTestId('map-viewport').boundingBox(), cx=box.x+box.width/2, cy=box.y+box.height/2
  const cdp = await context.newCDPSession(page)
  await cdp.send('Input.dispatchTouchEvent', {type:'touchStart', touchPoints:[{x:cx-30,y:cy,id:1},{x:cx+30,y:cy,id:2}]})
  await cdp.send('Input.dispatchTouchEvent', {type:'touchMove', touchPoints:[{x:cx-65,y:cy,id:1},{x:cx+65,y:cy,id:2}]})
  await cdp.send('Input.dispatchTouchEvent', {type:'touchEnd', touchPoints:[]})
  await page.waitForFunction(() => parseInt(document.querySelector('.map-reader-tools output').textContent) > 150)
  console.log('phone: native browser two-finger pinch passed')
  await context.close()
} finally { await browser.close() }
